#!/usr/bin/env bash
# =============================================================================
# new-service.sh
# Scaffold struktur direktori dan file untuk service baru
#
# Usage: bash new-service.sh <service_name> <tier>
# TIER: proxy | backend | devops
#
# Dipanggil oleh: make new-service NAME=myapp TIER=backend
# =============================================================================
set -euo pipefail

NAME="${1:?ERROR: service name required}"
TIER="${2:?ERROR: tier required. Options: proxy | backend | devops}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SERVICE_DIR="${ROOT_DIR}/${NAME}"

# Validasi tier
case "${TIER}" in
    proxy|backend|devops) ;;
    *)
        echo "ERROR: Invalid TIER '${TIER}'. Options: proxy | backend | devops"
        exit 1
        ;;
esac

# Cek apakah service sudah ada
if [ -d "${SERVICE_DIR}" ]; then
    echo "ERROR: Directory '${SERVICE_DIR}' already exists."
    exit 1
fi

echo "==> Scaffolding new service: '${NAME}' (tier: ${TIER})"

# Tentukan network berdasarkan tier
case "${TIER}" in
    proxy)
        PRIMARY_NETWORK="infra-proxy-net"
        EXTRA_NETWORK=""
        ;;
    backend)
        PRIMARY_NETWORK="infra-backend-net"
        EXTRA_NETWORK=""
        ;;
    devops)
        PRIMARY_NETWORK="infra-devops-net"
        EXTRA_NETWORK=""
        ;;
esac

# Buat direktori
mkdir -p "${SERVICE_DIR}"/{config,data}
echo "    Created directory structure: ${NAME}/{config,data}"

# Buat docker-compose.yml
cat > "${SERVICE_DIR}/docker-compose.yml" << COMPOSE
# =============================================================================
# ${NAME} — docker-compose.yml
# Tier: ${TIER}
# Generated by: make new-service NAME=${NAME} TIER=${TIER}
# =============================================================================

services:
  ${NAME}:
    image: vendor/${NAME}:VERSION_PIN_REQUIRED   # WAJIB: pin ke versi spesifik, jangan :latest
    container_name: ${NAME}                       # WAJIB: digunakan oleh wait-healthy.sh
    restart: unless-stopped
    env_file:
      - ../_shared/.env      # Global variables (BASE_DOMAIN, TZ, dll)
      - .env                 # Service-specific variables
    networks:
      - ${PRIMARY_NETWORK}
    volumes:
      - ./data:/app/data     # Sesuaikan mount point dengan image
    mem_limit: \${${NAME^^}_MEM_LIMIT}
    cpus: \${${NAME^^}_CPUS}
    healthcheck:
      # WAJIB: gunakan health check yang benar-benar memverifikasi fungsionalitas
      # Jangan hanya cek port — cek response aktual dari service
      test: ["CMD-SHELL", "GANTI_DENGAN_PERINTAH_HEALTH_CHECK_YANG_TEPAT"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      # ---- Traefik routing (uncomment jika service perlu HTTPS access) ----
      # - "traefik.enable=true"
      # - "traefik.http.routers.${NAME}.rule=Host(\`${NAME}.\${BASE_DOMAIN}\`)"
      # - "traefik.http.routers.${NAME}.entrypoints=websecure"
      # - "traefik.http.routers.${NAME}.tls.certresolver=step-ca"
      # - "traefik.http.services.${NAME}.loadbalancer.server.port=PORT"
      # ---- Observability (uncomment saat Loki/Prometheus stack deployed) ----
      # - "logging=promtail"
      # - "logging_jobname=${NAME}"

networks:
  ${PRIMARY_NETWORK}:
    external: true
  # infra-proxy-net:    # uncomment jika service ini juga perlu di-expose via Traefik
  #   external: true
COMPOSE

# Buat .env.template
cat > "${SERVICE_DIR}/.env.template" << ENVTEMPLATE
# =============================================================================
# ${NAME} — Service-specific environment variables
# Global variables (BASE_DOMAIN, TZ, dll) ada di _shared/.env.template
# =============================================================================

# Resource limits — tambahkan ke _shared/.env.template
# ${NAME^^}_MEM_LIMIT=512m
# ${NAME^^}_CPUS=0.5
ENVTEMPLATE

# Buat README.md
cat > "${SERVICE_DIR}/README.md" << SVCREADME
# ${NAME}

Service tier: **${TIER}**

## Configuration

- \`docker-compose.yml\` — Container definition
- \`.env.template\` — Service-specific environment variables
- \`config/\` — Service configuration files
- \`data/\` — Persistent data (gitignored)

## Integration

- Bergabung ke network: \`${PRIMARY_NETWORK}\`
- Global variables di-source dari: \`../_shared/.env\`

## Health Check

Service ini memiliki health check yang memverifikasi [DESKRIPSIKAN FUNGSI].

## Notes

[Tambahkan catatan konfigurasi spesifik di sini]
SVCREADME

echo "    Created: ${NAME}/docker-compose.yml"
echo "    Created: ${NAME}/.env.template"
echo "    Created: ${NAME}/README.md"

echo ""
echo "==> Service '${NAME}' scaffolded successfully!"
echo ""
echo "    NEXT STEPS (wajib dilakukan manual):"
echo "    1. Edit ${NAME}/docker-compose.yml:"
echo "       - Ganti image vendor/${NAME}:VERSION_PIN_REQUIRED dengan image aktual"
echo "       - Sesuaikan volume mount points"
echo "       - Isi health check command yang tepat"
echo "       - Uncomment Traefik labels jika perlu di-expose"
echo "    2. Tambahkan ${NAME^^}_MEM_LIMIT dan ${NAME^^}_CPUS ke _shared/.env.template"
echo "    3. Tambahkan step start di Makefile target 'up' (pada posisi yang tepat)"
echo "    4. Tambahkan step di Makefile target 'down'"
echo "    5. Jika ada data persisten, tambahkan backup script di _shared/scripts/backup/"
echo "    6. Jalankan: make init (untuk render .env baru)"
echo ""
echo "    Referensi: _shared/docs/ADDING_SERVICE.md"
